### ISSUE TITLE
quaternion elements mismatch in sample code

### ISSUE THREAD

**Issue by blackccpie** [JosephRedfern/VarienseVMU#3]
https://github.com/JosephRedfern/PyVMU/blob/dd607a3e586d4fa7e56d6e6443ef47d68be25f5f/examples/plot_quaternion.py#L40

Hi, I presume there is a little mismatch in your `plot_quaternion.py` sample, I think the correct code should be:

`ts, w, x, y, z = pkt`

Am I correct?

**Comment by JosephRedfern** [comment]
Oops -- you're quite right. Well spotted.

 I'll get this fixed soon.

Thank you,
Joe
